sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeaway
    username: root
    password: 123456

  redis:
    host: 192.168.153.128
    port: 6379
    password: aip036
    database: 1

  giett:
    access-token: b9284d75444e55a0507284d121ac60de
    owner: Aip0_o
    pero: imgs

  wechat:
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://626aaa8b.r11.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://626aaa8b.r11.cpolar.top/notify/refundSuccess

wx:
  miniapp:
    configs:
    - appid: wx225967b795f9f509
      secret: 5824b8574435f77826327f6f90ee85c1
      msg-data-format: JSON
